### ISSUE TITLE
sync fullnode with archive mode stuck

### ISSUE THREAD

**Issue by barryz** [maticnetwork/bor#113]
Hi team,

Bor sync process stuck with error:

```
Mar 30 14:53:48  bash[109786]: INFO [03-30|14:53:48.454] Fetching state sync events               queryParams="from-id=552&to-time=1597662416&limit=50"
Mar 30 14:53:48  bash[109786]: ERROR[03-30|14:53:48.456]
Mar 30 14:53:48  bash[109786]: ########## BAD BLOCK #########
Mar 30 14:53:48  bash[109786]: Chain config: {ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, YOLO v1: <nil>, Engine: bor}
Mar 30 14:53:48  bash[109786]: Number: 3299968
Mar 30 14:53:48 bash[109786]: Hash: 0xe66c096439cbe39d62157bbb1c8d34d7c990f8328bf19887fcd3aab68423d717
Mar 30 14:53:48  bash[109786]:          0: cumulative: 170395 gas: 170395 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0xa187a4c4744f16a67fa9a1afcd87897787e3a6633674dd3af54729ca67b97ae3 logs: [0xc0006ba790 0xc0006ba840] bloom: 00000000000000000008000000000000000000000000000000000000000000000000000000000000000080000000000000008000000000000040000200000000000000000000000000020000000000800000000000000000000100000002000000000000000000000000000000000000000000000000000080000000000000000000000000000400000000000000000040000000000000000000002000000000200000000000000000000010000000000000000000000000000000000000004000000000000000000001000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000010000000000100100 state:
Mar 30 14:53:48  bash[109786]: Error: invalid merkle root (remote: 73d7ada375cd8731c3a452e683faef9097c737160b8f8fa89b234ab024e28533 local: 52b6fbd9c1cf5e4f1653678c3f44dd42ba9423d11bea1a23e9baecc41166c5db)
Mar 30 14:53:48  bash[109786]: ##############################
Mar 30 14:53:48  bash[109786]:
Mar 30 14:53:48  bash[109786]: WARN [03-30|14:53:48.456] Synchronisation failed, dropping peer    peer=317b056032dfea66 err="retrieved hash chain is invalid: invalid merkle root (remote: 73d7ada375cd8731c3a452e683faef9097c737160b8f8fa89b234ab024e28533 local: 52b6fbd9c1cf5e4f1653678c3f44dd42ba9423d11bea1a23e9baecc41166c5db)"
```

I try to restart the bor service several times but not work.

```
Bor
Version: 1.9.16-stable
Git Commit: a1b7e2fcbbd753210e2c264bac633e2acd61839c
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.15.5
Operating System: linux
GOPATH=/root/go
GOROOT=/root/.go
```

**Comment by delroybosco** [comment]
Hey @barryz 

It seems that your Bor version is not up to date. Please upgrade your bor version to the latest one. You can read our Forum post to know how you can upgrade your Bor: https://forum.matic.network/t/bor-upgrade-v0-2-4/628

Also, when you face this issue it could happen because your Heimdall is not in sync with your Bor. So please do check if your Heimdall is running as well. Mostly, restarting the Bor service should resolve the problem but if it doesn't, please check your Heimdall service and see if it is syncing correctly.

**Comment by barryz** [comment]
Thanks for the reply @delroybosco, I will try to upgrade the bor version up to date.  Like you said above, My Heimdalld service also stopped while bor is not syncing.

**Comment by delroybosco** [comment]
Restarting your Heimdall service should do the trick. Do let me know if you run into any further problems.

**Comment by barryz** [comment]
After upgrade Bor to v0.2.4, the issue described as above still happens. 

Also, The Heimdall service does not work as well. I try to restart the Heimdall service, but not work.  The logs of the Heimdall service list as below:

```
Mar 30 16:51:01 x systemd[1]: Started heimdalld.
Mar 30 16:51:02 x heimdalld[125364]: I[2021-03-30|16:51:02.019] starting ABCI with Tendermint                module=main
Mar 30 16:51:02 x heimdalld[125364]: I[2021-03-30|16:51:02.106] Starting multiAppConn                        module=proxy impl=multiAppConn
Mar 30 16:51:02 x heimdalld[125364]: I[2021-03-30|16:51:02.106] Starting localClient                         module=abci-client connection=query impl=localClient
Mar 30 16:51:02 x heimdalld[125364]: I[2021-03-30|16:51:02.106] Starting localClient                         module=abci-client connection=mempool impl=localClient
Mar 30 16:51:02 x heimdalld[125364]: I[2021-03-30|16:51:02.106] Starting localClient                         module=abci-client connection=consensus impl=localClient
Mar 30 16:51:02 x heimdalld[125364]: I[2021-03-30|16:51:02.106] Starting EventBus                            module=events impl=EventBus
Mar 30 16:51:02 x heimdalld[125364]: I[2021-03-30|16:51:02.106] Starting PubSub                              module=pubsub impl=PubSub
Mar 30 16:51:02 x heimdalld[125364]: I[2021-03-30|16:51:02.111] Starting IndexerService                      module=txindex impl=IndexerService
Mar 30 16:51:02 x heimdalld[125364]: I[2021-03-30|16:51:02.111] ABCI Handshake App Info                      module=consensus height=1239130 hash=36DEAD5F6A4D0778C98072C71CA529DEDA5958D4C4A278458977A4895BD3E7AA software-version= protocol-version=0
Mar 30 16:51:02 x heimdalld[125364]: I[2021-03-30|16:51:02.111] ABCI Replay Blocks                           module=consensus appHeight=1239130 storeHeight=1239131 stateHeight=1239130
Mar 30 16:51:02 x heimdalld[125364]: I[2021-03-30|16:51:02.111] Replay last block using real app             module=consensus
Mar 30 16:51:02 x heimdalld[125364]: D[2021-03-30|16:51:02.114] [Peppermint] Applying block                  module=consensus height=1239131 numTxs=0
Mar 30 16:51:02 x heimdalld[125364]: D[2021-03-30|16:51:02.117] slashing is not enabled. To enable, send a proposal via governance module=x/slashing
Mar 30 16:51:02 x heimdalld[125364]: D[2021-03-30|16:51:02.117] [sidechannel] Processing side block          module=main height=1239131 targetHeight=1239129
Mar 30 16:51:02 x heimdalld[125364]: D[2021-03-30|16:51:02.117] [sidechannel] Approved side-tx               module=main txHash=7272c083fc937b71664c87121032fa8a2fdeedcf270e1e49ed381628b5cac773
Mar 30 16:51:02 x heimdalld[125364]: D[2021-03-30|16:51:02.120] Persisting span state                        module=bor sideTxResult=Yes
Mar 30 16:51:17 x systemd[1]: heimdalld.service: Main process exited, code=killed, status=9/KILL
Mar 30 16:51:17 x systemd[1]: heimdalld.service: Failed with result 'signal'.
Mar 30 16:51:22 x systemd[1]: heimdalld.service: Scheduled restart job, restart counter is at 2.
Mar 30 16:51:22 x systemd[1]: Stopped heimdalld.
Mar 30 16:51:22 x systemd[1]: Started heimdalld.
```

```
root@x:/tmp# heimdalld version
0.2.0
```

Maybe should upgrade Heimdall up to date?

**Comment by delroybosco** [comment]
Great :)
