### ISSUE TITLE
Support PUSH0 EVM opcode

### ISSUE THREAD

**Issue by SKYBITDev3** [maticnetwork/bor#994]
# Rationale
When trying to deploy a contract to Polygon (mainnet or Mumbai) that was compiled with the latest Solidity version (0.8.21), it fails with error `invalid opcode: PUSH0`.

Please update Polygon blockchain so that developers can deploy their contracts that were compiled with the latest Solidity version.

**Comment by manav2401** [comment]
Hi @SKYBITDev3, so according to our governance process, we have pushed the milestone hardfork (named Aalborg) first and as it's quite critical, we haven't enabled Shanghai changes into it. We have all the geth upstream changes but the Shanghai changes (e.g. PUSH0 opcode as you requested) aren't enabled. Those will go in a different hardfork just after the Aalborg one. Hope this clarifies your concern. Thanks!

**Comment by SKYBITDev3** [comment]
OK thanks @manav2401, so when can we expect the Shanghai changes to happen?

**Comment by manav2401** [comment]
At the moment, we're planning the Aalborg HF for mainnet in October so expect Shanghai after that. I can't commit on any specific dates as of now as it will go through the governance process.

**Comment by manav2401** [comment]
Seems answered, closing this.

**Comment by SKYBITDev3** [comment]
When can we expect `PUSH0` to work on Mumbai?

I still can't deploy to Mumbai using latest EVM as I get error:
> invalid opcode: PUSH0
